### PR TITLE
Added some chord types

### PR DESCRIPTION
**Pull request by federicomrc**

### CODE REVIEW

**Comment by federicomrc** [comment]
No problem, I'll update my PR ;)
I chose to use the Δ symbol to avoid clusters of "m" as in Ammaj7 or in AmM7, which to me are a little inconvenient to read at a glance. Perhaps the symbol "-" (the minus on the keyboard) could be used to denote a minor chord, which would prevent such clusters. 
What do you think?

**Comment by bragefuglseth** [comment]
I see how that can look a little messy. That notation is used in a lot of places, though, so I think most guitarists are used to it, *and* it’s already how those chord names are stored in the database. I’d like to avoid having to reformat it :)

**Comment by federicomrc** [comment]
Sorry for being late, I updated all the names using Δ as requested, they now use maj7.

**Comment by bragefuglseth** [comment]
Great, thank you so much! I'm currently working on other areas of the app, but will merge this before releasing the next update. Thanks again!

**Pull request merged**
